[WIP]add analytics example
fs/android-examples pull request #23
Opened 2017-06-08 11:00 UTC by yaroslavsudnik

2017-06-09 12:17 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/App.java
> +        analyticsHelper.addLogger(new FlurryAgentLogger(this));
Вот, теперь то, что нужно!

2017-06-09 12:17 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/EventLogger.java
> +    void simpleEvent();
хм, не понял как работает. 

Как мне отправить событие "Нажал на кнопку логин" ? 

Тут как будто пустое событие отправляется

2017-06-09 12:17 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/EventLogger.java
> +    void paramEvent(String paramKey, String paramValue);
А как тут название эвента передать? 
А как передать несколько параметров?

2017-06-09 12:17 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/FlurryAgentLogger.java
> +    private static final String FLURRY_APIKEY = "W34TS7S5WM6PY9BR6RH9";
Это должно быть в конструкторе.

2017-06-09 12:17 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/FlurryAgentLogger.java
> +    private static final String FLURRY_APIKEY = "W34TS7S5WM6PY9BR6RH9";
Представь, что это библиотека. И я не могу менять файл FlurryAgentLogger

2017-06-09 12:18 UTC, RamilGabdrakhmanov commented
Перед тем, как начать исправлять, обсуди как решать каждый из комментариев

2017-06-15 08:50 UTC, RamilGabdrakhmanov requested changes

2017-06-15 08:50 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/AnalyticsHelper.java
> +    public static class User {
Move in separate file

2017-06-15 08:50 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/GoogleAnalyticsLogger.java
> +                .setCategory(eventCategory)
Why not `.setAction?`

2017-06-20 15:58 UTC, RamilGabdrakhmanov requested changes

2017-06-20 15:58 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/App.java
> +    public static AnalyticsHelper analyticsHelper;
Сделай AnalyticsHelper синглтоном, пожалуйста. 

Там где нужно будет отправить событие нужно будет просто написать: AnalyticsHelper.get().log(...)

2017-06-20 15:58 UTC, RamilGabdrakhmanov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/util/CrashlyticsLogger.java
> +        Answers.getInstance().logCustom(new CustomEvent(event));
Для того, чтобы видеть события в крешах, также отправляй `Crashlytics.log(s)`;

2017-06-30 15:00 UTC, almaziskhakov requested changes

2017-06-30 15:00 UTC, almaziskhakov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/App.java
> +        AnalyticsHelper.setup();
вывести все содержимое в онкрите в метод `initAnalytics()`

2017-06-30 15:00 UTC, almaziskhakov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/MainActivity.java
> +    private String          simpleEvent;
отступы лишние

2017-06-30 15:00 UTC, almaziskhakov commented on AnalyticsExample/app/src/main/java/com/flatstack/analytics/MainActivity.java
> +    private final String SCREEN_NAME = "mainScreen";
переименовать в TAG = "MainActivity", так точно понятно в каком классе находимся, и в некоторых методах (особенно в фрагментах) часто используется таги

2017-07-11 12:56 UTC, almaziskhakov approved these changes

2020-05-29 07:44 UTC, closed without merging